### ISSUE TITLE
Correct handling of 404 error during .pdf parsing

### ISSUE THREAD

**Issue by KMax** [ailabitmo/sempubchallenge2014-task1#46]
```
[TASK http://ceur-ws.org/Vol-250/paper_34.pdf][PARSER parsers.publication_parser.PublicationNumOfPagesParser] Error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "CeurWsParser/spider.py", line 80, in task_initial
    p.parse()
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/base.py", line 71, in parse
    eval('self.' + method_name + '()')
  File "<string>", line 1, in <module>
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/publication_parser.py", line 265, in parse_template_1
    pdf = PdfFileReader(f)
  File "/usr/lib/python2.7/site-packages/PyPDF2/pdf.py", line 913, in __init__
    self.read(stream)
  File "/usr/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1464, in read
    line = self.readNextEndLine(stream)
  File "/usr/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1705, in readNextEndLine
    stream.seek(-2, 1)
IOError: [Errno 22] Invalid argument
[TASK http://ceur-ws.org/Vol-250/paper_34.pdf][PDFParser] Error parsepaper_34.pdf
Traceback (most recent call last):
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/pdf_parser.py", line 116, in parse_template_1
    first_page = convert_pdf_to_txt(self.data['file_location'])
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/pdf_parser.py", line 71, in convert_pdf_to_txt
    check_extractable=True):
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfpage.py", line 121, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "/usr/lib/python2.7/site-packages/pdfminer/pdfdocument.py", line 334, in __init__
    raise PDFSyntaxError('No /Root object! - Is this really a PDF?')
PDFSyntaxError: No /Root object! - Is this really a PDF?
[TASK http://ceur-ws.org/Vol-250/paper_34.pdf][PARSER PDFParser] with parse_template_1
[TASK http://ceur-ws.org/Vol-250/paper_34.pdf][PARSER parsers.pdf_parser.PDFParser] Error: 'countries'
Traceback (most recent call last):
  File "CeurWsParser/spider.py", line 80, in task_initial
    p.parse()
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/base.py", line 85, in parse
    self.write()
  File "/home/kolchinmax/RnD/sempubchallenge2014-task1/CeurWsParser/parsers/pdf_parser.py", line 89, in write
    self.task.url, len(self.data['countries']), len(self.data['universities']))
KeyError: 'countries'
[TASK http://ceur-ws.org/Vol-250/paper_34.pdf] ==== finished ====
```

**Comment by KMax** [comment]
Not a bug. We observe this issue if the SPARQL endpoint with the DBpedia dumps is not accessible.
